[toc]

# 使用Django的查询的setup问题

```shell
# 如下的错误
AppRegistryNotReady: Apps aren't loaded yet


# 解决方法
# Django
from django import db, core
from django.apps.registry import apps

# 重新setup
try:
    apps.check_apps_ready()
except core.exceptions.AppRegistryNotReady:
    import django

    django.setup()

# 一定要在Django的库使用之前setup
from django_q.models import Schedule
from django_q.tasks import async_task

from django_q.conf import logger
```



# multiprocessing on windows上运行的问题

```shell
# 错误
[out]:
Traceback (most recent call last):
  File "myfile.py", line 21, in <module>
    foo.do_multiprocessing()
  File "myfile.py", line 11, in do_multiprocessing
    self.process_2.start()
  File "...\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "...\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "...\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "...\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "...\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object
Doing 1


# reference
https://stackoverflow.com/questions/58775927/python3-behavior-of-multiprocessing-module-under-different-enviorments?noredirect=1&lq=1
https://stackoverflow.com/questions/62830911/typeerror-cannot-pickle-weakref-object/65749012

# 解决
# This is not OS related problem. The problem is the Python version. I'm running your code on Windows with Python 3.6.6 and it works fine but fails for Python 3.9 (for Windows). You also have 3.6 for Ubuntu but 3.8 for Windows thus indicating for this.

class A:
    def __init__(self):

      # ==== case 1 =====
      # Ubuntu: ok, Windows: ok
      a = multiprocessing.Process(target=self.t, args=())
      a.start()
      a = multiprocessing.Process(target=self.t, args=())
      a.start()
      # ================

      # ==== case 2 ====
      # Ubuntu: ok, Windows: ok
      self.b = multiprocessing.Process(target=self.t, args=())
      self.b.start()
      self.b = multiprocessing.Process(target=self.t, args=())
      self.b.start()
      # ================

      # ==== case 3 ====
      # Ubuntu: ok, Windows: Runtime Error
      c = multiprocessing.Process(target=self.t, args=())
      c.start()
      self.d = multiprocessing.Process(target=self.t, args=())
      self.d.start()
      # ================

      # ==== case 4 ====
      # Ubuntu: ok, Windows: ok
      self.e = multiprocessing.Process(target=self.t, args=())
      self.e.start()
      f = multiprocessing.Process(target=self.t, args=())
      f.start()
      # ================

      # ==== case 5 ====
      # Ubuntu: ok, Windows: Runtime Error
      self.g = [multiprocessing.Process(target=self.t, args=()) for _ in range(2)]
      for proc in self.g:
          proc.start()
      # ================

      # ==== case 6 ====
      # Ubuntu: ok, Windows: ok
      h = [multiprocessing.Process(target=self.t, args=()) for _ in range(2)]
      for proc in h:
          proc.start()
      # ================

      time.sleep(1) 

    def t(self):
        print("Hi")


if __name__ == "__main__":
    A()



```





